#:schema node_modules/wrangler/config-schema.json
name = "nextjs-blog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages 专用输出目录配置
pages_build_output_dir = ".open-next"

# 这里的 [vars] 可以放你的环境变量（可选）
[vars]
# NEXT_PUBLIC_API_URL = "https://api.example.com"