import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import FloatingNav from "./components/FloatingNav";
import { Providers } from "./providers";
import ThemeToggle from "./components/ThemeToggle";
import { LayoutGroup } from "framer-motion";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Wm1NlkN's Blog",
  description: "Generated by create next blog",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="zh" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <Providers>

           
            <div className="fixed top-6 inset-x-0 flex justify-center z-[70] pointer-events-none">
              <div className="pointer-events-auto">
                <FloatingNav />
              </div>
            </div>
         

            <nav className="sticky top-0 z-50 bg-white/70 backdrop-blur-md border-zinc-200 text-zinc-900 
            dark:bg-[#121212]/50 dark:border-white/10 dark:text-white flex justify-between items-center px-8 py-6 w-full text-sm">
              <div className="max-w-7xl mx-auto w-full flex justify-between items-center">
                <span className="font-bold tracking-tighter text-lg">
                  Wm1NlkN
                </span>
                <div className="text-zinc-500 hover:text-zinc-900 dark:hover:text-white cursor-pointer transition-colors">
                  登录
                </div>
              </div>
            </nav>

            <div className="pt-20">
              {children}
            </div>

            <div className="fixed bottom-8 right-8 z-50">
              <ThemeToggle />
            </div>

            <footer className="w-full py-8 flex flex-col items-center justify-center border-t border-zinc-900">
              <p className="text-zinc-600 text-xs tracking-wider">
                Copyright © 2026 - Now
              </p>
              <p className="text-zinc-700 text-[10px] mt-2 uppercase tracking-widest">
                Powered by Next.js & Motion-primitives, hosted on Vercel.
              </p>
            </footer>

          </Providers>
      </body>
    </html>
  );
}
